config:
  send_anonymous_usage_stats: false
  use_colors: true
  partial_parse: true
  printer_width: 80
  write_json: true
  warn_error: true
  log_format: text
  debug: false
  version_check: false
  fail_fast: true
  use_experimental_parser: false
  static_parser: true

brigade_analytics:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('dbt_dbhost') }}"
      user: "{{ env_var('dbt_dbuser') }}"
      password: "{{ env_var('dbt_dbpass') }}"
      port: 5432
      dbname: "{{ env_var('dbt_dbname') }}" # or database instead of dbname
      schema: public
      threads: 1
      keepalives_idle: 0 # default 0, indicating the system default. See below
      connect_timeout: 10 # default 10 seconds
      retries: 1  # default 1 retry on error/timeout when opening connections
      ### database-specific connection details
 
